apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argo
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: loki-stack
    targetRevision: 2.10.2
    helm:
      values: |
    loki:
      image:
        tag: 2.9.7
      persistence:
        enabled: true
        storageClassName: gp2-csi # insert storage class for the data volume
        size: 20Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
