apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-csi2
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
volumeBindingMode: WaitForFirstConsumer
