services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - frontend
      - backend

  db:
    image: mongo:7.0.11
    networks:
      - backend

  nginx:
    image: costumnginx
    ports:
      - "8085:80" 
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
#      - ./app/static:/usr/share/nginx/html/static
    networks:
      - frontend
    depends_on:
      - backend


networks:
  backend:
  frontend: